const data = [
    {
        id: 1,
        title: "Ristretto",
        img: "https://i.ytimg.com/vi/FDybEJFglWE/maxresdefault.jpg",
        price: 170,
        detail: "Corto e intenso",
        ml: 15,
        stock: 30,
        category: "clasicos",
    },
    {
        id: 2,
        title: "Espresso",
        img: "https://th.bing.com/th/id/OIP.Z89CjOARe5bTGsH3DpR9UwHaEc?pid=ImgDet&rs=1",
        price: 200,
        detail: "Clásico",
        ml: 60,
        stock: 30,
        category: "clasicos",
      },
      {
        id: 3,
        title: "Espresso doppio",
        img: "https://th.bing.com/th/id/OIP.wQzrPyLsOjZ5deodARcZVwHaGq?pid=ImgDet&rs=1",
        price: 250,
        detail: "Doble shot de sabor",
        ml: 15,
        stock: 20,
        category: "clasicos",
      },
      {
        id: 4,
        title: "Lungo",
        img: "https://www.columbuscafe.com/wp-content/uploads/2020/03/NOE02364-scaled-e1584972797277.jpg",
        price: 200,
        detail: "Shot de espresso largo",
        ml: 50,
        stock: 20,
        category: "clasicos",
      },
      {
        id: 5,
        title: "Americano",
        img: "https://www.cubaneandoconmario.com/wp-content/uploads/2017/01/Caf%C3%A9-americano.jpg",
        price: 300,
        detail: "Doble shot de espresso con agua filtrada",
        ml: 120,
        stock: 30,
        category: "clasicos",
      },
      {
        id: 6,
        title: "Café con panna",
        img: "https://th.bing.com/th/id/R.4b2c660ec0bf06583b31565a39bcdb8a?rik=N%2bUgjz6EiuPm5g&pid=ImgRaw&r=0",
        price: 330,
        detail: "Doble shot de espresso con crema batida",
        ml: 120,
        stock: 12,
        category: "clasicos",
      },
      {
        id: 7,
        title: "Latte",
        img: "https://th.bing.com/th/id/R.b9e4e2bce786805ddb2cbd458d92ce9c?rik=XInrKZBZzJxy2w&riu=http%3a%2f%2fwww.aerolatte.com%2fwp-content%2fuploads%2f2020%2f02%2fthree-layer-mochiato.jpg&ehk=n9S184%2fQGP0CEpWqd%2br%2fiVaX%2f%2fbzqH9MpNhJuPMiApA%3d&risl=&pid=ImgRaw&r=0",
        price: 350,
        detail: "Shot de espresso con leche texturizada",
        ml: 240,
        stock: 20,
        category: "clasicos",
      },
      {
        id: 8,
        title: "Mocha",
        img: "https://joaniesimon.com/wp-content/uploads/2016/01/homemade-mocha-e1452548176858.jpg",
        price: 400,
        detail: "Latte con base de chocolate negro o blanco",
        ml: 240,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 9,
        title: "Vienés",
        img: "https://monkites.com/wp-content/uploads/cafe-vienes3.jpg",
        price: 200,
        detail: "Doble shot espresso con espuma de leche y crema batida",
        ml: 200,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 10,
        title: "Flat White",
        img: "https://thecoffeevine.com/wp-content/uploads/2013/10/img_5753.jpg",
        price: 350,
        detail: "Doble shot de espresso con leche texturizada",
        ml: 160,
        stock: 20,
        category: "especialidad",
      },
      {
        id: 11,
        title: "Macchiato",
        img: "https://www.acouplecooks.com/wp-content/uploads/2020/10/how-to-make-a-macchiato-005.jpg",
        price: 200,
        detail: "Doble shot de espresso con espuma de leche",
        ml: 50,
        stock: 20,
        category: "clasicos",
      },
      {
        id: 12,
        title: "Capuccino",
        img: "https://th.bing.com/th/id/R.faeff4116594aa219c65dbd4a8386ae5?rik=Rie2k5wWq08tgQ&riu=http%3a%2f%2frazaitaliana.com%2fwp-content%2fuploads%2f2019%2f08%2fcapuccino2.jpg&ehk=9uys26rHf3R4qFfumpolVDq9qIClVdmG%2fIHW9fcI6YM%3d&risl=&pid=ImgRaw&r=0",
        price: 350,
        detail: "Shot de espresso con leche texturizada y espuma de leche",
        ml: 240,
        stock: 20,
        category: "clasicos",
      },
      {
        id: 13,
        title: "Irlandés",
        img: "https://cdn.kiwilimon.com/recetaimagen/36985/46347.jpg",
        price: 400,
        detail: "Doble shot de espresso con whiskey y crema batida",
        ml: 150,
        stock: 20,
        category: "especialidad",
      },
      {
        id: 14,
        title: "Bombón",
        img: "https://th.bing.com/th/id/OIP.S6co4HHBamgsO7OVYmAloAHaEK?pid=ImgDet&rs=1",
        price: 500,
        detail: "Shot de espresso, leche condensada, leche texturizada y barra de chocolate",
        ml: 200,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 15,
        title: "Doppio nutella",
        img: "https://www.ed.cl/wp-content/uploads/2015/04/Caf%C3%A9.jpg",
        price: 450,
        detail: "Doble shot de espresso recubierto por nutella",
        ml: 240,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 16,
        title: "Spicy Honey",
        img: "https://www.sugarandsoul.co/wp-content/uploads/2021/04/cafe-con-miel-recipe-5.jpg",
        price: 400,
        detail: "Doble ristretto, jarabe de miel, garam masala y leche texturizada",
        ml: 240,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 17,
        title: "Frapuccino",
        img: "https://caitlincooks.files.wordpress.com/2011/07/img_1345-e1310138988360.jpg",
        price: 450,
        detail: "Doble shot de espresso, leche, hielo y syrup de chocolate",
        ml: 240,
        stock: 20,
        category: "especialidad",
      },
      {
        id: 18,
        title: "Affogato",
        img: "https://th.bing.com/th/id/OIP.f241bBFYF_2Vr10UE4Vt6AHaFB?pid=ImgDet&rs=1",
        price: 450,
        detail: "Doble shot de espresso con dos bochas de helado de vainilla",
        ml: 300,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 19,
        title: "Rastafari",
        img: "https://img.cocinarico.es/2021-02/coctel-de-cafe-y-whisky-1.jpg",
        price: 500,
        detail: "Doble shot de espresso con whiskey, leche condensada y leche texturizada",
        ml: 340,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 20,
        title: "Espresso tonic",
        img: "https://th.bing.com/th/id/R.6e41030cea61d237784325aeccef9b0d?rik=jlUt%2fGMLcgV2dQ&pid=ImgRaw&r=0",
        price: 550,
        detail: "Doble shot de espresso con tónica y rodaja de naranja, pomelo o limón",
        ml: 200,
        stock: 12,
        category: "especialidad",
      },
      {
        id: 21,
        title: "Té",
        img: "https://th.bing.com/th/id/OIP.pRQRRAo_OjTa6IGu8320kgHaEc?pid=ImgDet&rs=1",
        price: 200,
        detail: "Consultar variedades de té",
        ml: 200,
        stock: 20,
        category: "otras",
      },
      {
        id: 22,
        title: "Submarino",
        img: "https://chocolateaguila.com/archivos/recetas/receta-222_submarino-de-dos-chocolates.jpg",
        price: 350,
        detail: "Leche caliente con barra de chocolate",
        ml: 240,
        stock: 12,
        category: "otras",
      },
      {
        id: 23,
        title: "Agua | Gaseosas",
        img: "https://brasaycarbon.pe/wp-content/uploads/2020/12/Gaseosa-CocaCola-medioL.jpg",
        price: 250,
        detail: "Agua o gaseosa línea Coca-Cola",
        ml: 500,
        stock: 30,
        category: "otras",
      },
      {
        id: 24,
        title: "Jugo de naranja",
        img: "https://th.bing.com/th/id/R.a9b8099bf9c9ca3d57cd0ac7196174ca?rik=Owmvnf2l%2fuYfsw&riu=http%3a%2f%2fstatic-1.ivoox.com%2faudios%2f0%2f0%2f2%2f2%2f9311608952200_XXL.jpg&ehk=qb8Jq0KkrENlIF0%2bqiwEBuQapoawqwZUrGgKz4MurMI%3d&risl=&pid=ImgRaw&r=0",
        price: 350,
        detail: "Jugo de naranja exprimida",
        ml: 400,
        stock: 20,
        category: "otras",
      },
      {
        id: 25,
        title: "Limonada",
        img: "https://i.pinimg.com/736x/3e/58/ae/3e58ae8a674ecefec86ba49465b738cd.jpg",
        price: 350,
        detail: "Limón, menta, jengibre y almibar",
        ml: 400,
        stock: 20,
        category: "otras",
      },

    ];


export function getProduct (){
      return new Promise(
        (resolve) => {
          setTimeout(() => resolve(data), 500);
        });
    }

export function getDetailProduct(id) {
      return new Promise((resolve) => {
        let cafePedido = data.find((item) => {
          return item.id === Number(id);
        });
        setTimeout(() => resolve(cafePedido), 500);
      });
    }    


export function getProductCategory (id){
  return new Promise((resolve) => {
    let arrayFilterProduct = data.filter(
      (item) => item.category === id
    );
    setTimeout(() => resolve(arrayFilterProduct), 500);
  });
}